---
# tasks file for k8s-master
- name: Copy kubeadm init config
  copy:
    src: kubeadm-init.yaml
    dest: /tmp/kubeadm-init.yaml
    owner: root
    group: root
    mode: 0644

- name: Initialize cluster with kubeadm
  command: kubeadm init --config=/tmp/kubeadm-init.yaml --v=5 --cri-socket=/run/containerd/containerd.sock

- name: Setup kubeconfig directory
  file:
    path: /home/noroot/.kube
    state: directory
    owner: noroot
    group: noroot
    mode: 0700

- name: Setup kube config file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/noroot/.kube/config
    remote_src: yes
    owner: noroot
    group: noroot
    mode: 0600

- name: Kubeconfig generator
  ansible.builtin.template:
    src: generateKubeconfig.sh
    dest: /home/noroot/generateKubeconfig.sh
    owner: noroot
    group: noroot
    mode: 0755

- name: Setup CNI
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  become: false

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  become: false

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  become: false

- name: Configure OIDC in API server
  ansible.builtin.template:
    src: kube-apiserver-manifest.yaml.j2
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    owner: root
    group: root
    mode: 0600
